services:
  mysql:
    container_name: calendar-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: calendar_db
      MYSQL_USER: calendar_user
      MYSQL_PASSWORD: calendar_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  localstack:
    container_name: calendar-localstack
    image: localstack/localstack:2.3.2
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - DEBUG=1
    ports:
      - "4566:4566"
    volumes:
      - localstack_tmp:/tmp/localstack
      - "${PWD}/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"

volumes:
  mysql_data:
  localstack_tmp: